### ISSUE TITLE
Read credentials from file instead of giving them on the cmd line

### ISSUE THREAD

**Issue by jkreileder** [maxileith/homebridge-appletv-enhanced#104]
### Current Situation

Currently credentials are passed to pyatv as arguments which means everyone can see them.
Most homebridge installations are probably de-facto single-user machines but still.

```
$ ps auxw | grep atv
homebri+  220395  0.0  0.7 150828 59472 ?        Sl   12:39   0:04 /var/lib/homebridge/appletv-enhanced/.venv/bin/python3 /var/lib/homebridge/appletv-enhanced/.venv/bin/atvscript -s 192.168.178.42 -i 52:E3:49:D3:9B:5A --airplay-credentials 6a2010[redacted] --companion-credentials 6a2010[redacted] push_updates
homebri+  220396  0.0  0.7 151020 59724 ?        Sl   12:39   0:05 /var/lib/homebridge/appletv-enhanced/.venv/bin/python3 /var/lib/homebridge/appletv-enhanced/.venv/bin/atvremote --scan-hosts 192.168.178.42 --companion-credentials 6a2010[redacted] --airplay-credentials 6a2010[redacted] cli
```

### Proposed Change

The pyatv documentation suggests that credentials can be read from files instead.

### Additional Context

This assumes files are not world-readable. For the homebridge Debian package this is true for `/home/homebridge/*` currently but not for `/var/lib/homebridge/*`. See https://github.com/homebridge/homebridge-apt-pkg/issues/20)

**Comment by maxileith** [comment]
HI @jkreileder,

I am aware that pyatv provides an option to manage credentials by itself via files. Actually, I have decided to not use this, since I want my plugin to have full control over the credentials:

https://github.com/maxileith/homebridge-appletv-enhanced/blob/a0dd0f41cfd0e441f0b9e775adf9b113dd5e0d15/src/appleTVEnhancedAccessory.ts#L1012

As you have already mentioned, the apt-package currently does not protect the homebridge directory ... so there is not even a security benefit to it, since everybody can access the homebridge directory and read the credentials from the files (doesn't matter if these are the credential files created by the plugin or pyatv).

Managing the credentials in the plugin also has some benefits for repairing an Apple TV in case the Homebridge has been removed from the device bridge on the Apple TV. Pyatv does not provide an option to forget credentials, thus the only option is to delete the file where pyatv stores the credentials ... not really a clean solution since this makes the assumption that pyatv is managing all the credentials stuff obsolete.
