### ISSUE TITLE
Sensors not available on third party home apps

### ISSUE THREAD

**Issue by wgalternate** [maxileith/homebridge-appletv-enhanced#149]
### Current Situation

Hi there,

Seems that the sensors are not being exposed when using third party apps such as Home Controller or Home+. Any thoughts on why that is? 

I would ideally like to set up more complex automations with multi state triggers such as “if _video_ and _playing_ is detected do this…”. Unfortunately the default Home app does not allow for such automations.

### Logs

```Markdown
-
```

### Configuration

```JSON
{
            "mediaTypes": [
                "music",
                "video"
            ],
            "deviceStates": [
                "paused",
                "playing",
                "stopped"
            ],
            "remoteKeysAsSwitch": [],
            "customInputURIs": [],
            "discover": {
                "unicast": [],
                "blacklist": [],
                "multicast": true
            },
            "name": "Apple TV Enhanced",
            "deviceStateDelay": 0,
            "avadaKedavraAppAmount": 15,
            "disableVolumeControlRemote": false,
            "forceVenvRecreate": false,
            "logLevel": 3,
            "_bridge": {
                "username": "***",
                "port": ***
            },
            "platform": "AppleTVEnhanced"
        }
```

### Environment

- OS: MacOS
- Docker: true
- Homebridge: 1.7.0
- Apple TV Enhanced: 1.0.0-2
- Node: 20.9.0

**Comment by maxileith** [comment]
To my knowledge, third party apps do not support television device. If you do know a plugin that manages to expose a television device that is also usable in third party apps, you can let me know and I will take a look at how they are doing that.

Since the motion sensors are exposed as services linked to the television device, they do not appear in third party home apps ... However, you can work around that with shortcut automations.
