### ISSUE TITLE
Is it possible to sort the input sources?

### ISSUE THREAD

**Issue by ahwman** [maxileith/homebridge-appletv-enhanced#17]
After customizing the input sources for each Apple TV, I noticed that the sort order is completely different on each Apple TV with no discernible pattern. Is it possible to sort the input sources between each Apple TV as muscle memory becomes an issue…

**Comment by maxileith** [comment]
Hi @ahwman ,

thank you for your enhancement request. In v0.3.1-beta.2 inputs are now created in alphabetical order. However, HomeKit on takes over this order when pairing the Apple TV. Thats simply a limitation of HomeKit.

So in order to get the alphabetical order you have to repair the plugin devices with your Home app. Additionally you need to unpair the external accessories (Apple TVs) in the Homebridge UI or delete the corresponding files in your drive.

Awaiting your Feeback @ahwman

**Comment by maxileith** [comment]
Correction: It does seem like they are only ordered in the initial pairing dialog. Sorry, but it does not seem like it is possible to sort them alphabetically. They are not event sorted by the internal identifiers that I am generating from hashing the app IDs like com.apple.settings.

Leaving as is, since having the Inputs in the initial pairing process sorted is a nice to have.

If anybody has a solution to that, feel free to comment.
