### ISSUE TITLE
Add AirPlay as an input

### ISSUE THREAD

**Issue by mark3apps** [maxileith/homebridge-appletv-enhanced#187]
### Analysis

While Airplaying to my TV music, it seems like it's unable to detect what's happening.

### Expected Behavior

It should show in the Inputs that it's currently Airplaying or show what app is currently open while airplaying.

### Steps To Reproduce

Airplay to a TV to play Music

### Logs

```console
Output from logs
Living Room Apple TV (XX:XX:XX:XX:XX:XX): Could not update the input to com.apple.TVAirPlay since the app is unknown.
```

### Configuration

```JSON
{
    "mediaTypes": [
        "music",
        "unknown",
        "video"
    ],
    "remoteKeysAsSwitch": [
        "pause",
        "play",
        "volume_down",
        "volume_up"
    ],
    "deviceStateDelay": 0,
    "platform": "AppleTVEnhanced",
    "_bridge": {
        "port": xxxxx,
        "username": "XX:XX:XX:XX:XX:XX"
    },
    "deviceStates": [
        "paused",
        "playing"
    ],
    "discover": {
        "unicast": [],
        "blacklist": [],
        "multicast": true
    },
    "name": "Apple TV Enhanced",
    "disableVolumeControlRemote": false,
    "forceVenvRecreate": false,
    "customInputURIs": [],
    "logLevel": 2,
    "avadaKedavraAppAmount": 15
}
```

**Comment by maxileith** [comment]
This is not really an error as the follwing log message is already indicating by beeing a warning ...

> ```logs
> Living Room Apple TV (XX:XX:XX:XX:XX:XX): Could not update the input to com.apple.TVAirPlay since the app is unknown.
> ```

I would consider this rather an enhancement. The goal would be to display something like "AirPlay: Spotify" as the currently selected input in HomeKit.

The reason that my plugin does not know the app `com.apple.TVAirPlay` is that the Apple TV itself does not report that it has this app. Why am I speaking of an app? I am pretty sure that AirPlay is a dedicated app on the Apple TV that just opend when a device connects to it and then it simply plays the content. So no matter what you are playing on the Apple TV, it is always the same app ...

So in order to achieve "AirPlay: Spotify" as the currently selected input, I have a special input for AirPlay which is renaming itself whenever the app that is airplaying to the AppleTV.

*Could you please install version v1.2.0-2 and test if everything works for you?*

**Comment by mark3apps** [comment]
The fact that I reported this yesterday and already it's doing what I want it to do is amazing.  I just tested it out with airplaying from the Apple Music App (the typical one I use) and it worked perfectly.  Curious, for homekit shortcuts, is there a way you could expose that current input name as a variable that can be selected in the "Get ____" Home Shortcut?  It would be great to be able to create automations and shortcuts based on the airplay names.

**Comment by maxileith** [comment]
> Also, I just wanna say, I love this plug in so much and really appreciate the effort and time you've put into it. Put my smart home to the next level.

Thank you! I really appreciate your warm words :heart:

> Curious, for homekit shortcuts, is there a way you could expose that current input name as a variable that can be selected in the "Get ____" Home Shortcut?

You can get the current input with "Get activity id" (or something similiar, I am not 100% sure because I have set my iPhone to german). Depending on the app there is a unique number which is generated by hashing the URI of the app.

In v1.2.0-2 this applies for the AirPlay input as well (of course).

Since version **v1.2.0-3** the identifier dynamically changes based on the app that is currently used to airplay. Could you check that and give me some Feedback?

**Comment by DataFran** [comment]
Maybe I'm messing up my automation settings, but what I'd love to be able to do here is trigger an automation when I airplay from my phone to the AppleTV. Is this possible with the current exposed sensors?
