### ISSUE TITLE
Apple TV Reset

### ISSUE THREAD

**Issue by alealibrandi** [maxileith/homebridge-appletv-enhanced#309]
### Preconditions

- [X] Requirements fulfilled
- [X] The known issues did not answer my question
- [X] The question has not been asked in the past or the answer does not satisfy me
- [X] There is currently no other opened issue that matches my question
- [X] I cannot find any answer to my question in GitHub discussions

### Current Situation

I had to reset the Apple TV to the factory configuration. After the reset, I can no longer pair the Apple TV.

### Logs

```console
[E] Apple TV Della Cameretta (A8:51:AB:0B:8E:AF): Unable to execute request 52: Traceback (most recent call last):File "/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.11/site-packages/pyatv/support/__init__.py", line 71, in error_handler
    return await func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.11/site-packages/pyatv/protocols/companion/protocol.py", line 120, in _setup_encryption
    await pair_verifier.verify_credentials()
  File "/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.11/site-packages/pyatv/protocols/companion/auth.py", line 150, in verify_credentials
    encrypted_data = self.srp.verify1(self.credentials, server_pub_key, encrypted)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.11/site-packages/pyatv/auth/hap_srp.py", line 101, in verify1
    raise exceptions.AuthenticationError("incorrect device response")
pyatv.exceptions.AuthenticationError: incorrect device response

The above exception was the direct cause of the following exception:

Traceback (most recent call last):File "/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.11/site-packages/pyatv/scripts/atvremote.py", line 978, in _run_application
    return await cli_handler(loop)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.11/site-packages/pyatv/scripts/atvremote.py", line 723, in cli_handler
    return await _handle_commands(args, config, storage, loop)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.11/site-packages/pyatv/scripts/atvremote.py", line 851, in _handle_commands
    atv = await connect(config, loop, protocol=args.protocol, storage=storage)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^File "/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.11/site-packages/pyatv/__init__.py", line 155, in connect
    await atv.connect()
  File "/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.11/site-packages/pyatv/core/facade.py", line 684, in connect
    if await setup_data.connect():
       ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.11/site-packages/pyatv/protocols/companion/__init__.py", line 571, in _connect
    await api.connect()
  File "/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.11/site-packages/pyatv/protocols/companion/api.py", line 143, in connect
    await self._protocol.start()
  File "/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.11/site-packages/pyatv/protocols/companion/protocol.py", line 108, in start
    await error_handler(self._setup_encryption, exceptions.AuthenticationError)
  File "/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.11/site-packages/pyatv/support/__init__.py", line 77, in error_handler
    raise fallback(str(ex)) from ex
pyatv.exceptions.AuthenticationError: incorrect device response

>>> An error occurred, full stack trace above
[08/03/2024, 20:10:26] [Apple TV Enhanced] [E] Apple TV Della Cameretta (A8:51:AB:0B:8E:AF): Error: Unable to execute request 52: Traceback (most recent call last):File "/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.11/site-packages/pyatv/support/__init__.py", line 71, in error_handler
    return await func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.11/site-packages/pyatv/protocols/companion/protocol.py", line 120, in _setup_encryption
    await pair_verifier.verify_credentials()
  File "/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.11/site-packages/pyatv/protocols/companion/auth.py", line 150, in verify_credentials
    encrypted_data = self.srp.verify1(self.credentials, server_pub_key, encrypted)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.11/site-packages/pyatv/auth/hap_srp.py", line 101, in verify1
    raise exceptions.AuthenticationError("incorrect device response")
pyatv.exceptions.AuthenticationError: incorrect device response

The above exception was the direct cause of the following exception:

Traceback (most recent call last):File "/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.11/site-packages/pyatv/scripts/atvremote.py", line 978, in _run_application
    return await cli_handler(loop)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.11/site-packages/pyatv/scripts/atvremote.py", line 723, in cli_handler
    return await _handle_commands(args, config, storage, loop)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.11/site-packages/pyatv/scripts/atvremote.py", line 851, in _handle_commands
    atv = await connect(config, loop, protocol=args.protocol, storage=storage)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^File "/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.11/site-packages/pyatv/__init__.py", line 155, in connect
    await atv.connect()
  File "/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.11/site-packages/pyatv/core/facade.py", line 684, in connect
    if await setup_data.connect():
       ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.11/site-packages/pyatv/protocols/companion/__init__.py", line 571, in _connect
    await api.connect()
  File "/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.11/site-packages/pyatv/protocols/companion/api.py", line 143, in connect
    await self._protocol.start()
  File "/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.11/site-packages/pyatv/protocols/companion/protocol.py", line 108, in start
    await error_handler(self._setup_encryption, exceptions.AuthenticationError)
  File "/var/lib/homebridge/appletv-enhanced/.venv/lib/python3.11/site-packages/pyatv/support/__init__.py", line 77, in error_handler
    raise fallback(str(ex)) from ex
pyatv.exceptions.AuthenticationError: incorrect device response

>>> An error occurred, full stack trace above
    at /var/lib/homebridge/node_modules/homebridge-appletv-enhanced/node_modules/@sebbo2002/node-pyatv/src/lib/tools.ts:172:15
    at Generator.next (<anonymous>)
    at o (/var/lib/homebridge/node_modules/homebridge-appletv-enhanced/node_modules/@sebbo2002/node-pyatv/dist/lib/index.cjs:1:627)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
```

### Configuration

```JSON
{
            "name": "Apple TV Enhanced",
            "mediaTypes": [
                "video"
            ],
            "deviceStates": [
                "paused",
                "playing"
            ],
            "deviceStateDelay": 0,
            "avadaKedavraAppAmount": 15,
            "customInputURIs": [
                "https://www.youtube.com/playlist?list=PLV338Zy6GfgfOTbkD7KI4KMElPb-l7jw5"
            ],
            "disableVolumeControlRemote": false,
            "setTopBox": false,
            "discover": {
                "multicast": true,
                "blacklist": [
                    "192.168.178.157",
                    "A8:51:AB:0B:8E:AF"
                ]
            },
            "forceVenvRecreate": false,
            "logLevel": 3,
            "updateCheckLevel": "stable",
            "deviceSpecificOverrides": [
                {
                    "overrideMediaTypes": false,
                    "overrideDeviceStates": false,
                    "overrideDeviceStateDelay": false,
                    "deviceStateDelay": 0,
                    "overrideRemoteKeysAsSwitch": false,
                    "overrideAvadaKedavraAppAmount": false,
                    "avadaKedavraAppAmount": 15,
                    "overrideCustomInputURIs": false,
                    "overrideDisableVolumeControlRemote": false,
                    "disableVolumeControlRemote": false,
                    "overrideSetTopBox": false,
                    "setTopBox": false
                }
            ],
            "_bridge": {
                "username": "0E:82:89:D9:8D:61",
                "port": 33254
            },
            "platform": "AppleTVEnhanced"
        }
```

### Operating System

Linux

### Operating System: Bits

64-bit

### Operating System: Distribution

Debian GNU/Linux

### Operating System: Distribution Version

12 (bookworm)

### Docker

no

### Docker Image

None

### Homebridge Version

1.7.0

### Homebridge Config UI Version

4.54.2

### Homebridge Storage Path

/var/lib/homebridge

### Homebridge Apple TV Enhanced Version

1.2.5

### Node Version

20.11.1

### NPM Version

10.2.4

### Python Version

3.11.2

### PIP Version

23.0.1

### Audio Output

no

### Same Subnet

yes

**Comment by ztalbot2000** [comment]
Paid a little more attention this time. The error happens as soon as its paired

**Comment by maxileith** [comment]
@alealibrandi fulfill the pre-checks if you expect an answer. The bot told you what to do.

**Comment by jondthompson** [comment]
The bot is useless other than to shuffle actual issues away from you. There's enough info in the initial post without the "pre-checks" to say it's a problem. I have the same problem. There's no way to delete an AppleTV once it's been added into your plugin. The plugin was asking my main AppleTV over and over again for the four digit code, which made my family annoyed as it was coming on screen in the middle of watching TV. I wanted to reset it in the app and see if that made it go away. Putting it in a child bridge seems to have handled it, but the issue is sound _without_ the checks.

**Comment by maxileith** [comment]
> The bot is useless other than to shuffle actual issues away from you.

Exactly, it shuffles issues away from me. I have spend hours and hours answering issues in this repository in my spare time. Issue occur for various reason but most of the issues that are opened here are trivial and are easily fixable by just complying with the requirements. In the past there were tediously long conversations just to find out that a version was outdated or the system architecture was not right or the Apple TV is not in the same subnet and so on ... Especially since many users that are roaming around here are not that deep into FOSS and have no development nor Linux experience. Once you will start your own open source project you will understand. For that reason I have written the bot. The bot makes sure that all requirements are fulfilled. If the requirements are fulfilled the issue is non-trivial and worth to take a look at. And once I go to GitHub and start looking at open issues I want to have everything in place, including debug logs ...

> There's no way to delete an AppleTV once it's been added into your plugin. The plugin was asking my main AppleTV over and over again for the four digit code, which made my family annoyed as it was coming on screen in the middle of watching TV. I wanted to reset it in the app and see if that made it go away. Putting it in a child bridge seems to have handled it, but the issue is sound without the checks.

And here we go again. I don't know why people just open issues instead of reading the README. You can deactivate multicast discovery and do it via unicast or just put your main Apple TV on the blacklist. Is it that hard to read the README?

**Comment by maxileith** [comment]
> I want the app to forget it has credentials for that particular AppleTV so that I can re-pair it.

You can revoke the credentials in the settings of the Apple TV. The plugin will detect that the credentials are no longer valid on a restart. It will automatically initiate a new pairing request to issue new credentials.

> Just like the OP needs to delete the credentials because they're no longer valid, as they reset their AppleTV and it created a new key sequence.

Not sure what you mean by "OP".

**Comment by maxileith** [comment]
@alealibrandi Have you fulfilled these requirements from the README?

> The access of Speakers & TVs should be either set to "Everybody" or "Anybody On the Same Network" in the Home app. 
Additionally, make sure to check the TV's HomeKit settings.

**Comment by ohhmyjawwsh** [comment]
@alealibrandi @jondthompson 

I also experienced this issue upon ATV reset & there is no way to revoke specific credentials from the settings on the Apple TV itself in order for the plugin to request a new pairing credential. If it is possible, it would need to be done through code with a connection to Xcode. Turning off/on AirPlay password requirements or AirPlay entirely did not fix this either. 

The manual solution @maxileith suggested was the way that worked well for me. 

For anyone who is reading this later on & is not familiar with code commands in Homebridge's Terminal, you would simply type "rm" before the file location/name for Terminal to process the request & delete file with the saved credentials.

Example:

rm ./appletv-enhanced/AABBCCDDEE/credentials.txt

Please note that when replacing AABBCCDDEE with the actual MAC address of your ATV, do not include any punctuations.

Please also note that you will not receive a confirmation message when it is deleted, it will just happen. You should see a new pairing code popup right away on the ATV if the plugin is still running & performs another discovery attempt. If not, reboot Homebridge or the child bridge & you should see the pairing code appear after the plugin starts back up & searches again for devices. 


Side note, @maxileith a great idea for the future would be to allow for users to manage saved credentials from inside the plugin interface instead of having to perform a manual code deletion of the file, which a large majority of the average Homebridge users would not know how to do. Another way other plugins I've used have done this is by adding the credentials to the JSON configuration file & I was easily able to find, edit or delete that line if needed, but I understand the importance of keeping it saved in a file within the directory for this plugin. Just a suggestion that it would be nice to essentially have a "reset" button of some kind within the interface for any current/past paired ATV's. 


I wish you all well & good luck.
