### ISSUE TITLE
Add most recent YouTube video to URI

### ISSUE THREAD

**Issue by bowenjfung** [maxileith/homebridge-appletv-enhanced#641]
### Preconditions

- [X] The feature has not been suggested in the past or it makes sense nowadays.

### Current Situation

This plugin is fantastic.

Custom URIs work very well for static content, but a common use case is to access the most recent video from a channel or playlist on platforms like YouTube.

### Proposed Change

My understanding is that it should be relatively straightforward to get the most recent video for a given channelID using the [YouTube Data API](https://developers.google.com/youtube/v3)  (see [here](https://stackoverflow.com/questions/55014224/how-can-i-list-the-uploads-from-a-youtube-channel/55031047#55031047)). This could then be passed as a custom URI in the config file. I think the only outstanding issue is how often the API is pinged.

**Comment by maxileith** [comment]
To get the latest video, you could just use the channel playlist, e.g. https://www.youtube.com/playlist?list=UUXuqSBlHAE6Xw-yeJA0Tunw

How to get the link is described here: https://www.reddit.com/r/LifeProTips/comments/247c2u/comment/kz3006w/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button

The feature is way to specific to be useful for most users. Besides that, there is no handle for YT Links on Apple TV since the YouTube app just does not implement that.
