### ISSUE TITLE
npm error notsup Actual cpu: arm

### ISSUE THREAD

**Issue by CooperCGN** [maxileith/homebridge-appletv-enhanced#837]
### Preconditions

- [X] Requirements fulfilled
- [X] The bug is not a known issue
- [X] The bug has not been solved in the past or the solution that was provided in the past does not work on my system
- [X] There is currently no other opened issue that describes this bug
- [X] I cannot find any solution to the problem in GitHub discussions
- [X] I am certain that the problem that I am having is a bug

### Analysis

Trying to update to latest version throws errors as shown in logs.

### Expected Behavior

Update without errors

### Steps To Reproduce

Trying to update from Config UI

### Logs

```console
USER: homebridge
DIR: /var/lib/homebridge
CMD: npm install --save homebridge-appletv-enhanced@1.10.4
⠙
⠹
⠸
⠼
⠴
⠦
⠧
⠇
⠏
⠋
npm error code EBADPLATFORM
⠋
npm error notsup Unsupported platform for homebridge-appletv-enhanced@1.10.4: wanted {"os":"linux,darwin","cpu":"x64,arm64"} (current: {"os":"linux","cpu":"arm"})
⠋
npm error notsup Valid os:   linux,darwin
npm error notsup Actual os:  linux
npm error notsup Valid cpu:  x64,arm64
npm error notsup Actual cpu: arm
⠋
npm error A complete log of this run can be found in: /home/homebridge/.npm/_logs/2024-12-30T04_02_48_721Z-debug-0.log
⠋


Error: Operation failed with code 1.

You can download this log file for future reference.

See https://github.com/homebridge/homebridge-config-ui-x/wiki/Troubleshooting for help.
```

### Configuration

```JSON
{
    "name": "Apple TV Enhanced",
    "deviceStates": [
        "idle",
        "paused",
        "playing"
    ],
    "deviceStateDelay": 0,
    "remoteKeysAsSwitch": [
        "menu",
        "turn_off",
        "turn_on",
        "top_menu"
    ],
    "avadaKedavraAppAmount": 15,
    "disableVolumeControlRemote": false,
    "absoluteVolumeControl": false,
    "setTopBox": false,
    "discover": {
        "multicast": true
    },
    "forceVenvRecreate": false,
    "logLevel": 2,
    "updateCheckLevel": "stable",
    "autoUpdate": "off",
    "updateCheckTime": 3,
    "deviceSpecificOverrides": [
        {
            "overrideMediaTypes": false,
            "overrideDeviceStates": false,
            "overrideDeviceStateDelay": false,
            "deviceStateDelay": 0,
            "overrideRemoteKeysAsSwitch": false,
            "overrideAvadaKedavraAppAmount": false,
            "avadaKedavraAppAmount": 15,
            "overrideCustomInputURIs": false,
            "overrideDisableVolumeControlRemote": false,
            "disableVolumeControlRemote": false,
            "overrideAbsoluteVolumeControl": false,
            "absoluteVolumeControl": false,
            "overrideSetTopBox": false,
            "setTopBox": false
        }
    ],
    "_bridge": {
        "username": "0E:87:96:D3:83:38",
        "port": 40406
    },
    "platform": "AppleTVEnhanced"
}
```

### Operating System

Linux

### Operating System: Bits

64-bit

### Operating System: Distribution

Raspian GNU/Linux

### Operating System: Distribution Version

11 bullseye

### Docker

no

### Docker Image

None

### Homebridge Version

1.8.5

### Homebridge Config UI Version

v4.67.0

### Homebridge Storage Path

/var/lib/homebridge

### Homebridge Apple TV Enhanced Version

1.10.3

### Node Version

v22.12.0

### NPM Version

10.9.0

### Python Version

3.9.2

### PIP Version

unknown

### Audio Output

no

### Same Subnet

yes

**Comment by maxileith** [comment]
@CooperCGN You are using a 32-bit OS which is not officially supported by the plugin as written in the requirements.

In the past, many issues were opened because of 32-bit specific errors, especially during the installation of python dependencies. Therefore, I have decided to add the 64-bit requirement to the package.json with the last update. Now npm will refuse to install the package on a 32-bit system.

To be clear, if you know what you are doing it is not that hard to install the plugin on a 32-bit system. However, many homebridge user just don't know what they are doing which leads to many opened issues that could be prevented just by fulfilling the 64-bit requirement.

**Comment by maxileith** [comment]
Now since npm refuses to install on 32-bit you cannot get it to work on 32-bit anymore. The solution is to fulfill the requirement that should have been fulfilled from the beginning and install a 64-bit OS.

Backup homebridge, flash the 64bit homebridge image onto an sd card, boot the pi, restore your homebridge config from a backup.

**Comment by maxileith** [comment]
Update: v1.10.5 of the plugin is installable on 32-bit systems again. Though, it is still not officially supported.
