### ISSUE TITLE
Home hubs have trouble getting active state

### ISSUE THREAD

**Issue by jkreileder** [maxileith/homebridge-appletv-enhanced#98]
### Analysis

In general this plugin works much better than the older ones. Thanks!

The only issue I have is that home hubs fail to read the active state. Home pods tell me that they couldn't query the state.  On Apple TVs I only notice it via an automation that pushes the active state of devices to an external service.

Getting the active state from iOS and MacOS works reliable.  Only tvOS and audioOS have problems.

### Expected Behavior

audioOS and tvOS should be able to read the active state.

### Steps To Reproduce

Ask a HomePod about the state of the Apple TV.
Or make an automation that pushes the state of the Apple TV to an HTTP endpoint.  Testing the automation on iOS or MacOS works.  But as soon as it runs on a HomePod or AppleTV it sends wrong values.

### Logs

```Markdown
n/a
```

### Configuration

```JSON
n/a
```

### Environment

- OS: Ubuntu 23.10
- Docker: false
- Homebridge: 1.7.0 (installed via apt)
- Apple TV Enhanced: v0.6.1
- Node: 18.18.2 (homebridge bundled)
- npm: 9.8.1 (homebridge bundled)
- Python: 3.11.6

**Comment by maxileith** [comment]
Hi @jkreileder ,

I have tried to reproduce the bug. How I did it ...

1. Create an Automation which sends an HTTP-Request to my Service that I use for Notifications
2. Turn on the Apple TV via Home ... the notification appears, thus the state is reported correctly
3. Turn on the Apple TV via the remote ... the notification appears, thus the state is reported correctly


So I cannot really reproduce the problems you are facing. Can you somehow narrow down the root cause. Is the bug only appearing in certain situations?

**Comment by jkreileder** [comment]
Here's what I do:

Get the states of several devices:
<img width="311" alt="Screenshot 2023-12-02 at 12 22 54" src="https://github.com/maxileith/homebridge-appletv-enhanced/assets/4390544/4399966e-8783-4aaf-aaa4-63e88fd50022">

Generate a body for a POST request:
<img width="308" alt="Screenshot 2023-12-02 at 12 23 16" src="https://github.com/maxileith/homebridge-appletv-enhanced/assets/4390544/d0c32a4c-856e-4855-b3f5-8a8e12e8c106">

Normalize the values to 0/1 and POST it:
<img width="307" alt="Screenshot 2023-12-02 at 12 23 35" src="https://github.com/maxileith/homebridge-appletv-enhanced/assets/4390544/74a977f3-69eb-4834-8a9c-d2f57e2255ca">

I trigger this automation every two minutes with a homebridge-schedule switch.

Testing the automation in the Home app always gets the correct state of "Apple TV Wohnzimmer". When the automation is triggered by the switch, it usually gets 0.  Sometimes (not sure under which circumstances) it switches to 1 and stays there for days.

I just noticed that Siri actually has problems getting the state on all devices:

<img width="332" alt="Screenshot 2023-12-02 at 12 40 52" src="https://github.com/maxileith/homebridge-appletv-enhanced/assets/4390544/7e7cac60-9e3e-40bd-bc5d-66e7998caa76">

although it should be available:
<img width="506" alt="Screenshot 2023-12-02 at 12 45 02" src="https://github.com/maxileith/homebridge-appletv-enhanced/assets/4390544/de2f481d-806d-44d6-8363-f0d908a200d8">

I'm pretty sure, the rest of the setup is OK.  With [homebridge-cmd-television](https://github.com/NorthernMan54/homebridge-cmd-television) this worked reliable.

**Comment by maxileith** [comment]
I think the problem is that your Regel is case sensitive. A test automation that I have just created works fine running on the hubs.

![image](https://github.com/maxileith/homebridge-appletv-enhanced/assets/44269066/328cce1e-b457-407c-a5f9-312216be0a3b)

![image](https://github.com/maxileith/homebridge-appletv-enhanced/assets/44269066/a76c012d-4829-47ea-900f-26b6f87bf818)
